
data_root = "/home/jovyan/workbench-shared-folder/bioblp/"
experiment_root = "data/benchmarks/experiments/DPI/"

[sampling]
outdir = "sampled"
num_negs_per_pos = 10
kg_triples_dir = "data/benchmarks/experiments/encoders/rotate/training_triples/"

[features]
outdir = "features"
transform = "concat"
missing_values = "mean"
encoders = ["noise", "structural", "complex", "rotate", "transe", "bioblpd", "bioblpm", "bioblpp" ]

[features.encoder_args.noise]
random_seed = 24

[features.encoder_args.structural]
proteins = "data/benchmarks/experiments/encoders/proteins"
molecules = "data/benchmarks/experiments/encoders/molecules"

[features.encoder_args.complex]
model_dir = "data/benchmarks/experiments/encoders/complex/"

[features.encoder_args.rotate]
model_dir = "data/benchmarks/experiments/encoders/rotate/"

[features.encoder_args.transe]
model_dir = "data/benchmarks/experiments/encoders/transe/"

[features.encoder_args.bioblpd]
model_dir = "data/benchmarks/experiments/encoders/bioblpd/"

[features.encoder_args.bioblpm]
model_dir = "data/benchmarks/experiments/encoders/bioblpm/"

[features.encoder_args.bioblpp]
model_dir = "data/benchmarks/experiments/encoders/bioblpp/"


[split]
n_splits = 5
outdir = "splits"


[models]


[models.rotate_mlp]
feature = "rotate"
model = "MLP"

[models.bioblpd_mlp]
feature = "bioblpd"
model = "MLP"

[models.bioblpm_mlp]
feature = "bioblpm"
model = "MLP"

[models.bioblpp_mlp]
feature = "bioblpp"
model = "MLP"


[train]
n_iter = 10
splits_file = "cv-splits.pt"
refit_params = ["AUCPR", "AUCROC"]
outdir = "models"
