
data_root = "/home/jovyan/workbench-shared-folder/bioblp/"
experiment_root = "data/benchmarks/experiments/dpi_fda/20230406-dev/"

[sampling]
outdir = "sampled"
num_negs_per_pos = 10
kg_triples_dir = "data/benchmarks/experiments/encoders/rotate/training_triples/"

[features]
outdir = "features"
transform = "concat"
missing_values = "random"
encoders = ["structural", "complex", "rotate", "noise"]

[features.encoder_args.noise]
random_seed = 24

[features.encoder_args.structural]
proteins = "data/benchmarks/experiments/encoders/proteins"
molecules = "data/benchmarks/experiments/encoders/molecules"

[features.encoder_args.complex]
model_dir = "data/benchmarks/experiments/encoders/complex/"

[features.encoder_args.rotate]
model_dir = "data/benchmarks/experiments/encoders/rotate/"

[features.encoder_args.transe]
model_dir = "data/benchmarks/experiments/encoders/transe/"

[models]

[models.transe_mlp]
feature = "transe"
model = "MLP"

[models.complex_mlp]
feature = "complex"
model = "MLP"

[train]
n_iter = 2
inner_n_folds = 2
outer_n_folds = 1
shuffle = true
refit_params = ["AUCPR", "AUCROC"]
outdir = "models"
