
data_root = "/home/jovyan/workbench-shared-folder/bioblp/"
experiment_root = "data/benchmarks/experiments/dpi_fda/"

[sampling]
outdir = "sampled"
num_negs_per_pos = 10
kg_triples_dir = "data/benchmarks/backbone_kg/"

[features]
outdir = "features"
transform = "concat"
missing_values = "random"
encoders = ["noise", "structural", "complex", "rotate"]


[features.encoder_args.noise]
random_seed = 24

[features.encoder_args.structural]
proteins = "data/benchmarks/experiments/encoders/proteins"
molecules = "data/benchmarks/experiments/encoders/molecules"

[features.encoder_args.complex]
model_dir = "data/benchmarks/experiments/encoders/complex/"

[features.encoder_args.rotate]
model_dir = "data/benchmarks/experiments/encoders/rotate/"

[features.encoder_args.transe]
model_dir = "data/benchmarks/experiments/encoders/transe/"

[models]
outdir = "models"

[models.noise_lr]
feature = "noise"
model = "LR"

[models.noise_rf]
feature = "noise"
model = "RF"

[models.noise_mlp]
feature = "noise"
model = "MLP"

[models.structural_lr]
feature = "structural"
model = "LR"

[models.structural_rf]
feature = "structural"
model = "RF"

[models.structural_mlp]
feature = "structural"
model = "MLP"

[train]
n_iter = 2
inner_n_folds = 3
outer_n_folds = 3
shuffle = true
refit_params = ["AUCPR", "AUCROC"]