model_registry_root_dir = "/home/jovyan/workbench-shared-folder/bioblp/models"#"../models"
#test_set_lists = ['test', 'valid']

[biokgb_graph]
biokgb_data_root_dir = "../data/biokgb"
graph_dir = "graph"  # relative to biokgb_data_root_dir
properties_dir = "properties"  # relative to biokgb_data_root_dir

[biokgb_graph.data_splits]
train = 'biokg.links-train.csv'
valid = 'biokg.links-valid.csv'  # relative to biokgb_graph.graph_dir
test = 'biokg.links-test.csv'
dummy = 'biokg.links-dummy.csv'

[biokgb_graph.properties]

[biokgb_graph.properties.entity_type_metadata_paths]
disease = "biokg.metadata.disease.tsv"  # relative to biokgb_properties.property_dir
protein = "biokg.metadata.protein.tsv"
drug = "biokg.metadata.drug.tsv"
pathway = "biokg.metadata.pathway.tsv"
genetic_disorder = "biokg.metadata.genetic_disorder.tsv"


[biokgb_graph.properties.entity_attribute_paths]
disease = "biokg_meshid_to_descr_name.tsv" # relative to biokgb_properties.property_dir
protein = "protein_embeddings_full_24_12_protid_idx_mapping.json"
drug = "biokg_molecule_embeddings_idx_mapping.json"
# drug = "biokg_molecule_embeddings.pt"

# model registry
[kge_models.registered_models]  # model directory path relative to model_registry_root_dir
rotate-otxtubeb = "rotate-otxtubeb"
bioblpd-38uz9fjs-16-03-2023 = "bioblpd-38uz9fjs-16-03-2023" 
bioblpd-38uz9fjs = "bioblpd-38uz9fjs" 
bioblpp-cttc3ucm = "bioblpp-cttc3ucm"
bioblpm-5rxz3k57 = "bioblpm-5rxz3k57"
rotate-bioblp-m-1r75g9na = "rotate-bioblp-m-1r75g9na" 
rotate-bioblp-p-4o6x9h96 = "rotate-bioblp-p-4o6x9h96"
