model_registry_root_dir = "/home/jovyan/workbench-shared-folder/bioblp/models"
#test_set_lists = ['test', 'valid']

[biokgb_graph]
biokgb_data_root_dir = "../data/biokgb"
graph_dir = "graph"  # relative to biokgb_data_root_dir
properties_dir = "properties"  # relative to biokgb_data_root_dir

[biokgb_graph.data_splits]
valid = 'biokg.links-valid.csv'  # relative to biokgb_graph.graph_dir
test = 'biokg.links-test.csv'
dummy = 'biokg.links-dummy.csv'

[biokgb_graph.properties]

[biokgb_graph.properties.entity_type_metadata_paths]
disease = "biokg.metadata.disease.tsv"  # relative to biokgb_properties.property_dir
protein = "biokg.metadata.protein.tsv"
# molecule = None

[biokgb_graph.properties.entity_attribute_paths]
disease = "biokg_meshid_to_descr_name.tsv" # relative to biokgb_properties.property_dir
protein = "protein_embeddings_full_24_12_protid_idx_mapping.json"
# molecule = None

# model registry
[kge_models]

#[kge_models.model_types]
#rotate = "rotate"
#bioblp_d = "bioblp_d"
#bioblp_p = "bioblp_p"

[kge_models.registered_models]  # model directory path relative to model_registry_root_dir
rotate-otxtubeb = "rotate-otxtubeb"
bioblpd-38uz9fjs = "bioblpd-38uz9fjs" 
bioblpp-cttc3ucm = "bioblpp-cttc3ucm"

